name: I2::Dev::Tests

on:
  push:
    branches: [master]

jobs:
  save-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Write Artifact
        run: echo "Hello world test" > my-artifact
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my-artifact
      - name: List directory contents
        if: always()
        run: pwd && ls -la
      - name: Print run ID
        if: always()
        run: echo ${{ github.run_id }}
    